CREATE TABLE FACTURAS
(
FACTURA INT IDENTITY(1,1) NOT NULL, --Generara un consecutivo de factura por cada ingreso de datos
[FECHA FACTURA] DATE,
[DOCUMENTO CLIENTE] VARCHAR(100),
[IVA 19%] NUMERIC(10,2),
TOTAL NUMERIC(10,2)
)


CREATE TABLE MANTENIMIENTOS
(
FACTURA INT PRIMARY KEY,
[DOC MECANICO] VARCHAR(100),
MANTENIMIENTOS VARCHAR(1000),
ESTADO VARCHAR (100)
)

CREATE TABLE MECANICOS
(
[PRIMER NOMBRE] VARCHAR (1000),
[SEGUNDO NOMBRE] VARCHAR (1000),
[PRIMER APELLIDO] VARCHAR (1000),
[SEGUNDO APELLIDO] VARCHAR (1000),
[TIPO DOCUMENTO] VARCHAR (10),
DOCUMENTO VARCHAR (100) PRIMARY KEY,
CELULAR INT,
DIRECCION VARCHAR(1000),
[CORREO ELECTRONICO] VARCHAR(1000),
ESTADO VARCHAR (100)
)

CREATE TABLE DET_CLIENTE_FACTURA
(
[PRIMER NOMBRE] VARCHAR (1000),
[SEGUNDO NOMBRE] VARCHAR (1000),
[PRIMER APELLIDO] VARCHAR (1000),
[SEGUNDO APELLIDO] VARCHAR (1000),
[TIPO DOCUMENTO] VARCHAR (10),
DOCUMENTO VARCHAR (100) PRIMARY KEY,
CELULAR INT,
DIRECCION VARCHAR(1000),
[CORREO ELECTRONICO] VARCHAR(1000)
)

CREATE TABLE REPUESTOS
(
FACTURA INT PRIMARY KEY,
REPUESTO VARCHAR(100),
[PRECIO UNIDAD] NUMERIC(10,2),
CANTIDAD INT,
DESCUENTO NUMERIC(10,2)
)

CREATE TABLE SERVICIOS
(
FACTURA INT PRIMARY KEY,
SERVICIO VARCHAR(100),
[PRECIO MANO OBRA] NUMERIC (10,2),
DESCUENTO NUMERIC(10,2)
)



/*
DROP TABLE FACTURAS
DROP TABLE MANTENIMIENTOS
DROP TABLE DET_CLIENTE_FACTURA
DROP TABLE REPUESTOS
DROP TABLE SERVICIOS
*/